language: csharp
mono: none
dist: xenial
dotnet: 3.1
install:
  - export COVERALLSNET_EXEPATH=/home/travis/build/csMACnz/coveralls.net/Package/Archive/linux/csmacnz.Coveralls
  - dotnet restore ./csmacnz.Coveralls.sln
script:
  - dotnet build ./csmacnz.Coveralls.sln -c Release
  - dotnet test ./src/csmacnz.Coveralls.Tests/csmacnz.Coveralls.Tests.csproj -c Release
  - dotnet publish ./src/csmacnz.Coveralls/csmacnz.Coveralls.csproj -f net5.0 -c Release -o "/home/travis/build/csMACnz/coveralls.net/Package/Archive/linux" -r linux-x64
  - dotnet test ./src/csmacnz.Coveralls.Tests.Integration/csmacnz.Coveralls.Tests.Integration.csproj -c Release